### ISSUE TITLE
Algo Not Working with other Pictures

### ISSUE THREAD

**Issue by sheikhrashid** [algorithmiaio/api-docs#20]
Hi,

I am using this algo **"algo://sfw/NudityDetection/1.1.4"** to find the Nudity in Pictures. It is working perfectly on the link you have given in sample.

**Working on This:**
http://www.isitnude.com.s3-website-us-east-1.amazonaws.com/assets/images/sample/young-man-by-the-sea.jpg
https://i.imgur.com/ajilbGq.jpg

But it is not working on my link.
**Not Working on This:**
https://parsefiles.back4app.com/vkimhy00uIlwZPs0pOiAy50a8yw83iWiWuDTZPu4/227235ff4803c54b1b772e6c237bfc82_IMG_20171212_164856_720.jpg

## **Update:**
It is working on every other link, but not working on the above one only.

Waiting for your reply.

Thanks,
Rashid

**Comment by peckjon** [comment]
Hi Rashid!

When I run the latter image directly at https://algorithmia.com/algorithms/sfw/NudityDetectioni2v it seems to be OK, returning {"nude": false, "confidence": 0.9202383273595842} indicating that it is pretty sure this image is non-nude.

Can you send us a codesample and the error you're getting so we can help debug?  Thanks!
