### ISSUE TITLE
Scala auth looks like Rust syntax 

### ISSUE THREAD

**Issue by StephanieKim** [algorithmiaio/api-docs#8]
import com.algorithmia.*
import com.algorithmia.algo.*

val client = Algorithmia::client("YOUR_API_KEY")

should be:
val client = Algorithmia.client("YOUR_API_KEY")

http://docs.algorithmia.com/?scala#authentication

**Comment by platypii** [comment]
Yup, also imports should be:

import com.algorithmia._
import com.algorithmia.algo._

**Comment by StephanieKim** [comment]
Oh snap should have caught that too since I have it compiling correctly lol thanks

**Comment by anowell** [comment]
I'm pretty sure my top compile errors in both Rust and Scala are writing code that uses the other language's syntax.

- does `match` go before or after the expression
- pattern match with or without the `case` keyword
- trailing commas recommened vs not allowed
- access static names with `.` vs `::`
- `val` vs `let` (and `var` vs `let mut`)
- semicolons
- Angle`<T>` vs square`[T]` brackets for generic types
- `Option.isDefined` vs `Option::is_some`
- the list goes on....
